from calculate_data.calculate_accel import ACCel_indexes, abs_max, abs_preact
from calculate_data.calculate_MVC import calculate_MVC_femoris, calculate_MVC_hamstring
from calculate_data.acc_limits import get_limits